<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-14T17:22:09 IST" name="Suite" finished-at="2023-12-14T17:22:35 IST" duration-ms="25862">
    <groups>
    </groups>
    <test started-at="2023-12-14T17:22:09 IST" name="Test" finished-at="2023-12-14T17:22:35 IST" duration-ms="25862">
      <class name="Testng.SoftAssert">
        <test-method is-config="true" signature="openAppln()[pri:0, instance:Testng.SoftAssert@28f3b248]" started-at="2023-12-14T17:22:23 IST" name="openAppln" finished-at="2023-12-14T17:22:26 IST" duration-ms="2840" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppln -->
        <test-method signature="test1()[pri:0, instance:Testng.SoftAssert@28f3b248]" started-at="2023-12-14T17:22:26 IST" name="test1" finished-at="2023-12-14T17:22:26 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="closeAppln()[pri:0, instance:Testng.SoftAssert@28f3b248]" started-at="2023-12-14T17:22:26 IST" name="closeAppln" finished-at="2023-12-14T17:22:26 IST" duration-ms="829" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppln -->
        <test-method is-config="true" signature="openAppln()[pri:0, instance:Testng.SoftAssert@28f3b248]" started-at="2023-12-14T17:22:26 IST" name="openAppln" finished-at="2023-12-14T17:22:30 IST" duration-ms="3151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppln -->
        <test-method signature="validLogin()[pri:0, instance:Testng.SoftAssert@28f3b248]" started-at="2023-12-14T17:22:30 IST" name="validLogin" finished-at="2023-12-14T17:22:34 IST" duration-ms="4049" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Facebook] but found [Facebook – log in or sign up]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Facebook] but found [Facebook – log in or sign up]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Testng.SoftAssert.validLogin(SoftAssert.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method is-config="true" signature="closeAppln()[pri:0, instance:Testng.SoftAssert@28f3b248]" started-at="2023-12-14T17:22:34 IST" name="closeAppln" finished-at="2023-12-14T17:22:35 IST" duration-ms="873" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppln -->
      </class> <!-- Testng.SoftAssert -->
      <class name="Testng.Assert">
        <test-method is-config="true" signature="openAppln()[pri:0, instance:Testng.Assert@1e6454ec]" started-at="2023-12-14T17:22:09 IST" name="openAppln" finished-at="2023-12-14T17:22:13 IST" duration-ms="3852" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppln -->
        <test-method signature="test1()[pri:0, instance:Testng.Assert@1e6454ec]" started-at="2023-12-14T17:22:13 IST" name="test1" finished-at="2023-12-14T17:22:13 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="closeAppln()[pri:0, instance:Testng.Assert@1e6454ec]" started-at="2023-12-14T17:22:13 IST" name="closeAppln" finished-at="2023-12-14T17:22:13 IST" duration-ms="920" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppln -->
        <test-method is-config="true" signature="openAppln()[pri:0, instance:Testng.Assert@1e6454ec]" started-at="2023-12-14T17:22:13 IST" name="openAppln" finished-at="2023-12-14T17:22:17 IST" duration-ms="3986" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppln -->
        <test-method signature="validLogin()[pri:0, instance:Testng.Assert@1e6454ec]" started-at="2023-12-14T17:22:17 IST" name="validLogin" finished-at="2023-12-14T17:22:22 IST" duration-ms="4497" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Facebook] but found [Facebook – log in or sign up]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Facebook] but found [Facebook – log in or sign up]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Testng.Assert.validLogin(Assert.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method is-config="true" signature="closeAppln()[pri:0, instance:Testng.Assert@1e6454ec]" started-at="2023-12-14T17:22:22 IST" name="closeAppln" finished-at="2023-12-14T17:22:23 IST" duration-ms="831" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppln -->
      </class> <!-- Testng.Assert -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
